
const ResponseConstants = {
    STATUS_CODE_SUCCESS: 0,
    STATUS_CODE_ERROR_INTERNAL_SERVER: 5,
    ERROR_UNPROCESSABLE_ENTITY: 2,
    E_SERVER_ERROR_PROCESS_CODE: 'E_SERVER_ERROR_PROCESS_CODE',
    E_SCRIPT_ERROR_PROCESS_CODE: 'E_SCRIPT_ERROR_PROCESS_CODE',
    E_SERVER_ERROR_UNKNOWN: 'E_SERVER_ERROR_UNKNOWN',
    E_MISSING_IMPLEMENTATION_MESSAGE: 'Error al obtener los formatos de descarga',
    E_VALIDATION_FAILURE: 'E_VALIDATION_FAILURE',
}

export default ResponseConstants